framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

        # MAILER_DNS=null://null will try to enqueue the message in both the sync and async queues,
        # creating a doublon, and making the tests fail.
        # keep this config until real config is set
        message_bus: false
